# Generated by Django 5.2.11 on 2026-06-20 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('response', models.JSONField()),
                ('provider', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ai_cache',
            },
        ),
        migrations.CreateModel(
            name='AIMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('endpoint', models.CharField(max_length=100)),
                ('request_time', models.FloatField()),
                ('tokens_used', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_metrics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAssignmentSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestions', models.JSONField()),
                ('criteria_used', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending Manager Review'), ('approved', 'Approved by Manager'), ('rejected', 'Rejected by Manager'), ('modified', 'Modified by Manager'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('manager_notes', models.TextField(blank=True, null=True)),
                ('feedback_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager_approved_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_suggestions', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ai_assignment_suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_ai_suggestion', models.BooleanField(default=False)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('manager_approved', models.BooleanField(default=True)),
                ('ai_reasoning', models.TextField(blank=True, null=True)),
                ('manager_notes', models.TextField(blank=True, null=True)),
                ('was_successful', models.BooleanField(default=True)),
                ('resolution_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_assignments', to=settings.AUTH_USER_MODEL)),
                ('suggested_by_ai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_assignments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='tickets.ticket')),
            ],
            options={
                'db_table': 'assignment_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(blank=True, default=dict)),
                ('years_experience', models.IntegerField(default=0)),
                ('avg_resolution_time', models.FloatField(blank=True, null=True)),
                ('success_rate', models.FloatField(blank=True, null=True)),
                ('tickets_completed', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('current_workload', models.IntegerField(default=0)),
                ('max_workload', models.IntegerField(default=5)),
                ('is_available', models.BooleanField(default=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('suggestion_accuracy', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'developer_profiles',
            },
        ),
    ]
